"""v0.7.0 regression tests — three correctness fixes.

Each test is written to be RED on the v0.6.0 baseline (the bug class it
targets) and GREEN after the fix:

* ``test_hashed_requirements_txt_resolves_dep_not_zero`` —
  fix-requirements-hashes-silent-drop: a ``pip-compile`` /
  ``--require-hashes`` requirements.txt (``name==1.0.0 --hash=sha256:...``
  per logical line, the DevSecOps pinned-requirements format) raised
  ``InvalidRequirement`` on every hashed line and was swallowed by
  ``except Exception: continue`` → ZERO deps resolved → exit 0, a silent
  full-tree under-scan / false-clean. RED: zero deps. GREEN: foo resolves.
* ``test_npm_range_no_match_does_not_resolve_to_latest`` —
  fix-npm-range-no-match-resolves-latest: an npm range spec (``^1.2.0``) with
  NO satisfying published version fell back to ``dist-tags.latest`` (necessarily
  OUTSIDE the range) and was fetched + scanned, false-passing the gate. RED:
  audits 2.0.0. GREEN: surfaces as ``range_unsatisfiable:<spec>`` coverage gap.
* ``test_npm_no_lockfile_404_recorded_as_unscanned_not_silent`` —
  fix-npm-no-lockfile-404-silent-drop: a 404'd/unreachable npm package on the
  no-lockfile path returned ``None`` from ``_resolve_npm_dist_tag`` and was
  silently ``continue``-d with no ``marker_skipped`` signal, vanishing from
  both ``packages`` and the coverage report. RED: in neither. GREEN:
  ``npm_doc_not_found`` coverage gap.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Make src/ importable when running pytest from the repo root without an
# editable install (mirrors tests/test_scanner.py).
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))


# --------------------------------------------------------------------------- #
# Test helpers (self-contained mirrors of the _FakeResponse stand-in in
# tests/test_scanner.py / test_v060_fixes.py — kept local so this module has
# no cross-test-module import coupling).
# --------------------------------------------------------------------------- #


class _FakeResponse:
    """Non-payload stand-in; iter_content serialises payload back to JSON bytes
    so the streaming + bounded read round-trips to the same dict the v0.5.0
    ``.json()`` path returned."""

    def __init__(self, *, status_code=200, payload=None):
        self.status_code = status_code
        self._payload = payload or {}

    def iter_content(self, chunk_size=65536):
        data = json.dumps(self._payload).encode("utf-8") if self._payload else b""
        for i in range(0, len(data), chunk_size):
            yield data[i : i + chunk_size]

    def json(self):
        return self._payload

    def raise_for_status(self):
        if self.status_code >= 400:
            import requests

            raise requests.HTTPError(f"{self.status_code}")


# --------------------------------------------------------------------------- #
# Fix 1 — fix-requirements-hashes-silent-drop
# --------------------------------------------------------------------------- #


def test_hashed_requirements_txt_resolves_dep_not_zero(tmp_path, monkeypatch):
    """fix-requirements-hashes-silent-drop: a pip-compile /
    ``--require-hashes`` requirements.txt (``name==1.0.0 --hash=sha256:...``
    per logical line, the DevSecOps pinned-requirements format) must resolve
    its dep — not ZERO. The v0.6.0 pre-processing only stripped ``#`` comments
    and ``--`` flag lines, NOT ``--hash`` tokens, so every hashed line raised
    ``InvalidRequirement`` and was swallowed by ``except Exception: continue``
    → zero deps resolved → exit 0, a silent full-tree under-scan / false-clean
    on the core surface. The fix joins backslash-continued physical lines and
    strips ``--hash`` / ``--hash=`` tokens before ``Requirement(line)`` parses
    the PEP 508 name@spec (mirrors how ``--`` flags are already stripped)."""
    import requests

    from promptaudit.resolver import resolve

    # pip-compile --generate-hashes output: one logical requirement per line,
    # --hash options spread across backslash-continued physical lines (the
    # canonical pinned-requirements format this tool's commercial audience
    # uses). A trailing-backslash continuation + inline --hash tokens both
    # break Requirement(line) on the v0.6.0 path.
    (tmp_path / "requirements.txt").write_text(
        "# This file is autogenerated by pip-compile\n"
        "# To update, run:\n"
        "#    pip-compile --generate-hashes\n"
        "foo==1.0.0 \\\n"
        "    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \\\n"
        "    --hash=sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
        encoding="utf-8",
    )

    def _fake_get(self, url, *a, **kw):
        # Exact-pin lookup: _walk_pypi fetches /pypi/foo/1.0.0/json.
        if url.endswith("/foo/1.0.0/json"):
            return _FakeResponse(
                status_code=200,
                payload={
                    "info": {"version": "1.0.0", "requires_dist": None},
                    "releases": {"1.0.0": []},
                },
            )
        return _FakeResponse(status_code=404)

    monkeypatch.setattr(requests.Session, "get", _fake_get)

    pkgs = list(resolve(tmp_path))
    foo = [p for p in pkgs if p.name == "foo"]
    assert foo, (
        "the hashed requirements.txt must resolve foo (pip-compile / "
        "--require-hashes format); got ZERO deps — the v0.6.0 path dropped "
        f"every --hash line as InvalidRequirement. resolved: {pkgs}"
    )
    assert foo[0].version == "1.0.0", foo[0].version
    assert foo[0].ecosystem == "pypi", foo[0].ecosystem


# --------------------------------------------------------------------------- #
# Fix 2 — fix-npm-range-no-match-resolves-latest
# --------------------------------------------------------------------------- #


def test_npm_range_no_match_does_not_resolve_to_latest(tmp_path, monkeypatch):
    """fix-npm-range-no-match-resolves-latest: an npm range spec with NO
    satisfying published version must NOT fall back to ``dist-tags.latest``
    (which is necessarily OUTSIDE the range, else it would itself be a
    candidate) and be audited. The v0.6.0 ``_resolve_npm_max_satisfying``
    returned ``dist-tags.latest`` when ``candidates`` was empty, so the
    no-lockfile walk fetched + scanned an un-installable version and, if clean,
    false-passed the CI gate. The fix mirrors PyPI's ``_PinFailed`` sentinel:
    surface the dep as a coverage gap (``range_unsatisfiable:<spec>``) instead.
    This is the npm-side analog of v0.6.0's
    ``fix-tilde-pin-lookup-failure-resolves-latest`` (PyPI ``~=`` side)."""
    import requests
    from packaging.version import Version

    from promptaudit.resolver import MarkerSkipped, _npm_range_matcher, resolve

    (tmp_path / "package.json").write_text(
        json.dumps({"name": "app", "dependencies": {"leftpad": "^1.2.0"}}),
        encoding="utf-8",
    )

    def _fake_get(self, url, *a, **kw):
        # Full registry document — only 0.9.0 and 2.0.0 published, NEITHER
        # satisfies ^1.2.0 (>=1.2.0,<2.0.0). dist-tags.latest=2.0.0 is the
        # out-of-range bait the v0.6.0 fallback would audit.
        if url.endswith("/leftpad"):
            return _FakeResponse(
                status_code=200,
                payload={
                    "dist-tags": {"latest": "2.0.0"},
                    "versions": {"0.9.0": {}, "2.0.0": {}},
                },
            )
        # Bait version doc — if the bug is present, the resolver fetches
        # /leftpad/2.0.0 (the out-of-range latest) and yields leftpad@2.0.0.
        if url.endswith("/leftpad/2.0.0"):
            return _FakeResponse(status_code=200, payload={"dependencies": {}})
        return _FakeResponse(status_code=404)

    monkeypatch.setattr(requests.Session, "get", _fake_get)

    skipped: list[MarkerSkipped] = []
    pkgs = list(resolve(tmp_path, marker_skipped=skipped))

    leftpad = [p for p in pkgs if p.name == "leftpad"]
    # Hard signal: leftpad must NOT be resolved to the out-of-range 2.0.0.
    assert not leftpad, (
        "leftpad ^1.2.0 with no satisfying published version must NOT resolve "
        "to the out-of-range dist-tags.latest 2.0.0; the v0.6.0 fallback would "
        f"audit an un-installable version. resolved: {leftpad}"
    )
    leftpad_versions = {p.version for p in pkgs if p.name == "leftpad"}
    assert "2.0.0" not in leftpad_versions, (
        f"2.0.0 must NOT be audited for a ^1.2.0 range nothing satisfies; "
        f"got versions {leftpad_versions}"
    )
    # And it must be surfaced as a coverage gap, not dropped silently.
    leftpad_skipped = [ms for ms in skipped if ms.name == "leftpad"]
    assert leftpad_skipped, (
        "leftpad range-unsatisfiable must surface as a coverage gap "
        f"(marker_skipped); skipped was {skipped}"
    )
    assert leftpad_skipped[0].marker == "range_unsatisfiable:^1.2.0", (
        leftpad_skipped[0].marker
    )
    assert leftpad_skipped[0].ecosystem == "npm", leftpad_skipped[0].ecosystem
    # Sanity: 2.0.0 is genuinely outside ^1.2.0 (and 1.9.9 would satisfy but
    # is not published), so auditing 2.0.0 would be a false-clean on the
    # "audit the version you actually install" promise.
    matcher = _npm_range_matcher("^1.2.0")
    assert not matcher(Version("2.0.0"))
    assert matcher(Version("1.9.9"))


# --------------------------------------------------------------------------- #
# Fix 3 — fix-npm-no-lockfile-404-silent-drop
# --------------------------------------------------------------------------- #


def test_npm_no_lockfile_404_recorded_as_unscanned_not_silent(
    tmp_path, monkeypatch
):
    """fix-npm-no-lockfile-404-silent-drop: a 404'd/unreachable npm package on
    the no-lockfile (package.json) path must be recorded in marker_skipped
    (``npm_doc_not_found``) — not silently dropped. The v0.6.0
    ``_resolve_npm_dist_tag`` returned ``None`` when the registry doc 404'd and
    ``_resolve_npm_package_json`` did ``if not version: continue`` with NO
    ``marker_skipped`` signal (unlike PyPI's ``_walk_pypi``), so a yanked /
    unpublished package — itself a supply-chain red flag — vanished from both
    ``packages`` and ``marker_skipped``: a silent under-scan. The fix threads
    ``marker_skipped`` into the npm no-lockfile walk and appends a
    ``npm_doc_not_found`` marker, mirroring PyPI's ``_walk_pypi`` handling."""
    import requests

    from promptaudit.resolver import MarkerSkipped, resolve

    (tmp_path / "package.json").write_text(
        json.dumps({"name": "app", "dependencies": {"ghost-dep": "^1.2.0"}}),
        encoding="utf-8",
    )

    def _fake_get(self, url, *a, **kw):
        # The whole-package registry doc 404s for every URL (yanked /
        # unpublished / unreachable) — _resolve_npm_dist_tag returns None.
        return _FakeResponse(status_code=404)

    monkeypatch.setattr(requests.Session, "get", _fake_get)

    skipped: list[MarkerSkipped] = []
    pkgs = list(resolve(tmp_path, marker_skipped=skipped))

    ghost = [p for p in pkgs if p.name == "ghost-dep"]
    # Hard signal: the 404'd package must NOT be resolved to a version.
    assert not ghost, f"a 404'd npm package must not be resolved; got {ghost}"
    # And it must be surfaced as a coverage gap, not dropped silently (the
    # v0.6.0 path left it in NEITHER packages NOR marker_skipped).
    ghost_skipped = [ms for ms in skipped if ms.name == "ghost-dep"]
    assert ghost_skipped, (
        "a 404'd npm package on the no-lockfile path must surface as a coverage "
        "gap (marker_skipped/npm_doc_not_found), not vanish silently; skipped "
        f"was {skipped}"
    )
    assert ghost_skipped[0].marker == "npm_doc_not_found", ghost_skipped[0].marker
    assert ghost_skipped[0].ecosystem == "npm", ghost_skipped[0].ecosystem
